import { Router } from 'express';
import { register, login, refresh, logout, profile } from '../controllers/auth.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.post('/register', register);
router.post('/login', login);
router.post('/refresh', refresh);
router.post('/logout', authenticate, logout);
router.get('/me', authenticate, profile);
export default router;
